config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :show]

  resources :bands do
    resources :albums, only: [:new]
    end

  resources :albums do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band_id, :album_type, presence: true
  validates :album_type, inclusion: ["Studio", "Live"]

  has_many :tracks,
  dependent: :destroy,
  class_name: :Track,
  primary_key: :id,
  foreign_key: :album_id

  belongs_to :band,
  class_name: :Band,
  primary_key: :id,
  foreign_key: :band_id

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  dependent: :destroy,
  class_name: :Album,
  primary_key: :id,
  foreign_key: :band_id

  has_many :tracks,
  class_name: :Track,
  through: :albums,
  source: :tracks
end

app/models/track.rb
class Track < ApplicationRecord
  validates :title, :album_id, presence: true
  validates :track_type, inclusion: ["Standard", "Bonus"]

  belongs_to :album,
    class_name: :Album,
    primary_key: :id,
    foreign_key: :album_id

  has_one :band,
    through: :album,
    source: :band
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return if user.nil?
    if user.is_password?(password)
      user
    else
      errors[:user] << "Wrong password"
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    Random.new.urlsafe_base64(16).html_safe
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    @session_token ||= User.generate_session_token
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find_by(id: params[:id])
    @tracks = Track.find_by(album_id: @album.id)
    render :show
  end

  def create
    @album = Album.new(album_params)
    if @album.save!
      redirect_to album_url(@album)
    else
      flash[:errors] << "Can't create this album"
      redirect_to album_new_url
    end
  end

  def update
    @album = Album.update_attributes(album_params)
    if @album.save!
      redirect_to album_url(@album)
    else
      flash[:errors] << "Can't update this album"
      redirect_to album_url(@album)
    end
  end

  def destroy
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :album_type, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in_user!(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end

  def logged_in?
    current_user
  end

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def log_out!
    session[:session_token] = User.generate_session_token
  end

  # def require_login
  #   unless logged_in?
  #     flash[:error] = "You must be logged in to access this section"
  #     redirect_to new_user_url
  #   end
  # end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
    render :new
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to band_url(@band)
    else
      flash[:errors] << "Can't create this band"
      redirect_to band_new_url
    end
  end

  def update
    @band = Band.update_attributes(band_params)
    if @band.save!
      redirect_to band_url(@band)
    else
      flash[:errors] << "Can't update this band"
      redirect_to band_url(@band)
    end
  end

  def destroy
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] << "log in failed"
      redirect_to new_user_url
    end
  end

  def destroy
    log_out!
    redirect_to new_user_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)
    if @track.save!
      redirect_to track_url(@track)
    else
      flash[:errors] << "Can't create this track"
      redirect_to new_track_url
    end
  end

  def update
    @track = Track.update_attributes(track_params)
    if @track.save!
      redirect_to track_url(@track)
    else
      flash[:errors] << "Can't update this track"
      redirect_to track_url(@track)
    end
  end

  def destroy
  end

  private
  def track_params
    params.require(:track).permit(:title, :lyrics, :ord, :track_type, :album_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_login, :show

  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save!
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash[:errors] <<"Can't create user"
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h1> Hiii , <%= @album.name%> !</h1>

<br><br>
<%@album.tracks.each do |track| %>

<%= link_to track.title, track_url(track.id)%>

<br><br>
<% end %>

app/views/albums/new.html.erb
<h2> Create new album </h2>

<form action = "<%=albums_url%>" method = "post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">

  <label for="title" value ="Album title">Album Title</label>
  <input type="text" name="album[title]" value="" placeholder="Insert title">
  <br><br>

  <label for="year" value="Year">Year</label>
  <input type="number" name="album[year]" min="1900" max="2100">
  <br><br>

  <label for="band" value="Band">Band</label>
  <select name="album[band_id]">
    <%@bands.each do |band|%>
      <option  value ="<%=band.id%>"> <%= band.name%> </option>
    <% end %>
  </select>
  <br><br>

  <label for="album type" value="Album Type">Album Type</label><br>
  <input type="radio" name="album[album_type]" value="Studio"> Studio<br>
  <input type="radio" name="album[album_type]" value="Live"> Live<br>

  <input type="Submit" name="" value="Create new album">
</form>

app/views/albums/show.html.erb
<h1>Welcome new album in our library! </h1>
<p> Name is <b><%= @album.title %></b> </p>
<p> Belongs_to this band <b><%= @album.band.name %></b> </p>
<p> Year <b><%= @album.year %></b> </p>
<p> Number of songs <b><%= @album.tracks.count %></b> </p>

<%= link_to "Band Page", band_url(@album.band.id) %>
<br><br>
<% @album.tracks.each do |track| %>
  <%= link_to track.title, track_url(track.id) %>
  <br><br>
<% end %>

app/views/bands/_band.html.erb
<h2> <%= link_to band.name, band_url(band.id) %> </h2>

app/views/bands/index.html.erb
<h1>All the bands!</h1>

<%= render @bands %>

app/views/bands/new.html.erb
<h1>Create new band</h1>

<form class="" action="/bands" method="post">
  <input type = "hidden" name="authenticity_token" value="<%= form_authenticity_token%>" method = "post">
  <label for="band name" value="Band name">
    <input type="text" name="band[name]" placeholder="band name">
  <input type="Submit" >
</form>

app/views/bands/show.html.erb
<h1> Hiii , <%= @band.name%> !</h1>

<%= link_to "Bands home page", bands_url%>
<br><br>
<%@band.albums.each do |album| %>

<%= link_to album.title, album_url(album.id)%>

<br><br>
<% end %>

<%= link_to "All Bands", bands_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <%= button_to 'Sign out', session_url, method: :delete %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

app/views/tracks/index.html.erb
<h1> Tracks, tracks, tracks </h1>

app/views/tracks/new.html.erb
<h1> Create new track !</h1>

<form class="" action="<%=tracks_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label for="Title">Title</label>
  <input type="text" name="track[title]" placeholder="Insert title">
  <br><br>

  <label for="album_id">Album</label>
  <select class="" name="track[album_id]">
    <%@albums.each do |album|%>
      <option value="<%=album.id%>"><%= album.title%></option>
    <%end%>
  </select>

  <br><br>
  <label for="track_type">Track type</label>
  <input type="radio" name="track[track_type]" value="Standard"> "Standard"<br>
  <input type="radio" name="track[track_type]" value="Bonus"> "Bonus"<br>

  <br><br>
  <label for="ord">Ord</label>
  <input type="number" name="track[ord]" min="1">

  <br><br>
  <label for="lyrics">Lyrics</label>
  <textarea name="track[lyrics]" rows="8" cols="80"></textarea>

  <br><br>
<input type="Submit">
</form>

app/views/tracks/show.html.erb
<h1>Welcome new track in our library!</h1>

<p>Track title <%=@track.title%><p>
<p>Track type <%=@track.track_type%><p>
<p>Want some lyrics?
    <textarea name="name" rows="8" cols="80">
      <%= @track.lyrics%>
    </textarea>
</p>

<%= link_to "Album", album_url(@track.album.id) %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<form action = <%= users_url %> method = "post" >
   <input type="hidden" name="authenticity_token" value = "<%=form_authenticity_token%>" method = "post">

  <label for="email" value = "email">
  <input type="text" name="user[email]" placeholder="email">
  <label for="password" value = "password">
  <input type="password" name="user[password]" placeholder="password">
  <input type="Submit">

</form>

app/views/users/show.html.erb
<h3> currently login <%= @user.email%> </h3>
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<h3> Hi , <%= @user.email%> ! What are you doing here?<h3>
<%= link_to "Explore Bands", bands_url %>
<br><br>
<%= link_to "Explore tracks", tracks_url %>